Add adsb.chaos-consulting.de
rickstaa/awesome-adsb pull request #18
Opened 2023-12-12 20:59 UTC by skymaker-c2is

Hey there,

we just came across this list and would like to be added to it.

Cheers
Lukas

2024-01-10 08:10 UTC, rickstaa commented
@skymaker-c2is, sorry for the late review; busy times 😅. Great find. I just confirmed that the website operates in the community space, not the commercial one, so everything checks out.

2024-01-10 08:11 UTC, rickstaa approved these changes

2024-01-10 08:14 UTC, rickstaa requested changes

2024-01-10 08:14 UTC, rickstaa commented on readme.md
> +- [adsb.chaos-consulting.de](https://adsb.chaos-consulting.de) - A flight/ship/radiosonde-tracker run by hobby ethusiasts. Focused on the feeding stations. Absolutely non-commercial.
How about:

```suggestion
- [adsb.chaos-consulting.de](https://adsb.chaos-consulting.de) - A non-commercial tracker for flights, ships, and radiosondes managed by enthusiasts. Focuses on the contributions of individual feeding stations.
```

I wanted to include the non-commercial inside the main description and remove the absolutely. Another option I am okay with would be `A non-commercial flight/ship/radiosonde-tracker run by hobby ethusiasts. Focused on the feeding stations`.

2024-01-10 08:14 UTC, rickstaa commented
@skymaker-c2is I added one comment, but after that is fixed, I will merge this pull request. Thanks again for the contribution 🚀.

2024-01-11 18:32 UTC, skymaker-c2is commented
Hey @rickstaa, the changes are fine! Thank you!

2024-01-11 19:25 UTC, merged

2024-01-11 19:25 UTC, rickstaa commented
@skymaker-c2is excellent! Thanks for the contribution. Merged into the main branch 🚀.

2024-01-11 19:31 UTC, rickstaa commented
Published under https://github.com/rickstaa/awesome-adsb/releases/tag/v1.1.1.